apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nOps-eks-cluster-dev
  region: us-east-1
  version: "1.25"
managedNodeGroups:
  - instanceType: m5.large
    amiFamily: AmazonLinux2
    name: nOps-eks-cluster-dev
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
iam:
  withOIDC: true
