apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    team: SRE-team
  requirements:
    # - key: "node.kubernetes.io/instance-type"
    #   operator: In
    #   values: [t2.small, t2.large, t2.xlarge, t2.2xlarge]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [us-east-1a, us-east-1b, us-east-1c] # Zones
    - key: karpenter.sh/capacity-type
      operator: In
      values: [spot]
  limits:
    resources:
      cpu: 1000
  provider:
    tags:
      team: SRE-team
    instanceProfile: KarpenterNodeInstanceProfile-nOps-eks-cluster-dev
  ttlSecondsAfterEmpty: 30
