name: Decommission EKS cluster

on:
  workflow_dispatch:

env:
  CLUSTER_NAME: "nOps-eks-cluster-dev"
  AWS_REGION: "us-east-1"

jobs:
  provision_eks:
    name: Decommission EKS cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubectl config
        run: aws eks update-kubeconfig --name nOps-eks-cluster-dev --region us-east-1

      - name: Set up eksctl
        run: |
          curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Delete iamserviceaccount
        run: |
          eksctl delete iamserviceaccount \
          --cluster $CLUSTER_NAME \
          --name karpenter \
          --namespace karpenter

      - name: Delete karpenter stack
        run: |
          aws cloudformation delete-stack \
          --stack-name Karpenter-$CLUSTER_NAME

      - name: Destroy EKS cluster
        run: eksctl delete cluster --name $CLUSTER_NAME --region $AWS_REGION
